// export interface InventoryPolicy {
//     ID: number;
//     owner_code: string;
//     use_lot_no: boolean;
//     use_case_no: boolean;
//     use_fifo: boolean;
//     use_fefo: boolean;
//     use_vas: boolean;
//     use_production_date: boolean;
//     use_receive_location: boolean;
//     use_serial_number: boolean;
//     use_carton_number: boolean;
//     use_case_number: boolean;
//     require_expiry_date: boolean;
//     require_lot_number: boolean;
//     show_rec_date: boolean;
//     require_scan_pick_location: boolean;
//     validation_sn : boolean;
//     require_picking_scan : boolean;
//     require_packing_scan : boolean;
//     allow_mixed_lot: boolean;
//     allow_negative_stock: boolean;
//     picking_single_scan:boolean;
//     require_receive_scan: boolean;
//     require_putaway_scan: boolean;
//     validate_receive_scan: boolean;
//     allocation_lot_by_order: boolean;
//     allocation_location_by_order: boolean;
// }

export interface InventoryPolicy {
  ID: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string | null;
  owner_code: string;
  use_lot_no: boolean;
  use_case_no: boolean;
  use_fifo: boolean;
  use_fefo: boolean;
  use_vas: boolean;
  use_production_date: boolean;
  use_receive_location: boolean;
  use_serial_number: boolean;
  use_carton_number: boolean;
  use_case_number: boolean;
  show_rec_date: boolean;
  require_expiry_date: boolean;
  require_lot_number: boolean;
  require_scan_pick_location: boolean;
  allow_mixed_lot: boolean;
  allow_negative_stock: boolean;
  validation_sn?: boolean;
  require_picking_scan?: boolean;
  require_packing_scan?: boolean;
  picking_single_scan?: boolean;
  require_receive_scan?: boolean;
  require_putaway_scan?: boolean;
  validate_receive_scan?: boolean;
  inbound_can_input_serial?: boolean;
  allocation_lot_by_order?: boolean;
  allocation_location_by_order?: boolean;
  allocation_case_by_order?: boolean;
  allocation_carton_by_order?: boolean;
  allocation_serial_by_order?: boolean;
  picking_with_scanner?: boolean;
  picking_exclude_locations_under_cycle_count?: boolean;
}